force-app/main/default/objects/Game_Unit__c/Game_Unit__c.object-meta.xml
<CustomObject>
    <label>Game Unit</label>
    <nameField>
        <displayFormat>GU-{0000}</displayFormat>
        <label>Game Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Unit_Item__c/Unit_Item__c.object-meta.xml
<CustomObject>
    <label>Unit Item</label>
    <nameField>
        <displayFormat>UI-{0000}</displayFormat>
        <label>Unit Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Item__c/fields/Game_Unit__c.field-meta.xml
<CustomField>
    <fullName>Game_Unit__c</fullName>
    <label>Game Unit</label>
    <referenceTo>Game_Unit__c</referenceTo>
    <relationshipLabel>Unit Items</relationshipLabel>
    <relationshipName>Unit_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GameSessionUnitWrapper.cls
public class GameSessionUnitWrapper extends BasicObjectWrapper{
    @AuraEnabled public String title;
    @AuraEnabled public String content;

    @AuraEnabled public List<GameSessionUnitItemWrapper> items;

    public GameSessionUnitWrapper(Game_Unit__c unit) {
        this.id         = unit.id;
        this.title      = unit?.Title__c;
        this.content    = unit?.Content__c;
        this.setUnitItems(unit.Unit_Items__r);
    }
    public void setUnitItems(List<Unit_Item__c> unitItems) {
        if (this.items == null) this.items = new List<GameSessionUnitItemWrapper>();
        for (Unit_Item__c item : unitItems) {
            this.items.add(new GameSessionUnitItemWrapper(item));
        }
    }
}