force-app/main/default/objects/Game_Session__c/Game_Session__c.object-meta.xml
<CustomObject>
    <label>Game Session</label>
    <nameField>
        <displayFormat>GS-{0000}</displayFormat>
        <label>Game Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Game Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Game_Session__c.field-meta.xml
<CustomField>
    <fullName>Game_Session__c</fullName>
    <label>Game Session</label>
    <referenceTo>Game_Session__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParticipantRegistrationService.cls
public with sharing class ParticipantRegistrationService {
    private final static Integer FIRST_ELEMENT = 0;

    private static ParticipantRegistrationService instance = null;
    private DMLHandler recordHandler = null;

    private ParticipantRegistrationService() {
        recordHandler = DMLHandler.getInstance();
    }
    public static ParticipantRegistrationService getInstance() {
        if (instance == null) instance = new ParticipantRegistrationService();

        return instance;
    }

    public Participant__c invokeSingular(String session, String nickname) {
        recordHandler.addNew(generateParticipant(session, nickname));

        recordHandler.commitWork();

        return getLastReply();
    }

    private Participant__c generateParticipant(String seesionId, String nickname) {
        return new Participant__c(
            Game_Session__c     = (Id)seesionId,
            Nickname__c         = nickname,
            Joined_DateTime__c  = DateTime.now()
        );
    }
    private Participant__c getLastReply() {
        return recordHandler.returnInsertedList().isEmpty() ? null : (Participant__c)recordHandler.returnInsertedList()[FIRST_ELEMENT];
    }
}