force-app/main/default/objects/Game_Session__c/Game_Session__c.object-meta.xml
<CustomObject>
    <label>Game Session</label>
    <nameField>
        <displayFormat>GS-{0000}</displayFormat>
        <label>Game Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/Game_Unit__c.object-meta.xml
<CustomObject>
    <label>Game Unit</label>
    <nameField>
        <displayFormat>GU-{0000}</displayFormat>
        <label>Game Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/fields/Game_Session__c.field-meta.xml
<CustomField>
    <fullName>Game_Session__c</fullName>
    <label>Game Session</label>
    <referenceTo>Game_Session__c</referenceTo>
    <relationshipLabel>Game Units</relationshipLabel>
    <relationshipName>Game_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Game_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GameUnitTriggerHandler.cls
public with sharing class GameUnitTriggerHandler extends TriggerHandler {
    private DMLHandler recordHandler = null;

    public GameUnitTriggerHandler() {
        super(GameUnitTriggerHandler.class.getName());

        recordHandler = DMLHandler.getInstance();
    }

    public override void beforeInsert() {
    }
    public override void afterInsert() {
    }
    public override void beforeUpdate() {
        completeGameUnit();
    }
    public override void afterUpdate() {
        recordHandler.commitWork();
    }

    public void completeGameUnit() {
        for (Game_Unit__c gu : (List<Game_Unit__c>)this.newList) {
            if (this.isChangedField(gu, 'Status__c') && gu.Status__c == 'Closed') {
                recordHandler.addEvent(
                    GameUnitHelper.generateCompletionEvent(gu.Game_Session__c, gu.Id)
                );
            }
        } 
    }

    public override Boolean isChangedField(sObject checkObject, String fieldName) {
        Game_Unit__c gu = (Game_Unit__c)checkObject;
        return (
                (this.oldList == null) ||
                (checkObject.get(fieldName) != this.oldMap.get(checkObject.Id).get(fieldName))
            );
    }
}