force-app/main/default/objects/Game_Session__c/Game_Session__c.object-meta.xml
<CustomObject>
    <label>Game Session</label>
    <nameField>
        <displayFormat>GS-{0000}</displayFormat>
        <label>Game Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Session__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Step</label>
    <referenceTo>Game_Unit__c</referenceTo>
    <relationshipLabel>Game Sessions</relationshipLabel>
    <relationshipName>Game_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game_Session__c/fields/Session_Code__c.field-meta.xml
<CustomField>
    <fullName>Session_Code__c</fullName>
    <externalId>true</externalId>
    <label>Session Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GameSessionWrapper.cls
global without sharing class GameSessionWrapper {
    public GameSessionWrapper(Game_Session__c session) {
        this.id = session.Id;
        this.sessionCode = session.Session_Code__c;
        if (session.Current_Step__c != null) this.currentStep = session.Current_Step__c;
    }
    @AuraEnabled public String id;
    @AuraEnabled public String currentStep;
    @AuraEnabled public String sessionCode;
}