force-app/main/default/objects/Game_Session__c/Game_Session__c.object-meta.xml
<CustomObject>
    <label>Game Session</label>
    <nameField>
        <displayFormat>GS-{0000}</displayFormat>
        <label>Game Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Session__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Step</label>
    <referenceTo>Game_Unit__c</referenceTo>
    <relationshipLabel>Game Sessions</relationshipLabel>
    <relationshipName>Game_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game_Session__c/fields/Session_Code__c.field-meta.xml
<CustomField>
    <fullName>Session_Code__c</fullName>
    <externalId>true</externalId>
    <label>Session Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Game_Unit__c/Game_Unit__c.object-meta.xml
<CustomObject>
    <label>Game Unit</label>
    <nameField>
        <displayFormat>GU-{0000}</displayFormat>
        <label>Game Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/fields/Game_Session__c.field-meta.xml
<CustomField>
    <fullName>Game_Session__c</fullName>
    <label>Game Session</label>
    <referenceTo>Game_Session__c</referenceTo>
    <relationshipLabel>Game Units</relationshipLabel>
    <relationshipName>Game_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DefaultGameWrapper.cls
public virtual class DefaultGameWrapper extends DefaultWrapper{
    private final static String REJECTED_STRING = 'No data found';

    public Game_Session__c session;

    @AuraEnabled public String sessionCode;

    @AuraEnabled public GameSessionUnitWrapper currentStep;

    public DefaultGameWrapper() {
        this.result = new DefaultWrapper.Result(null, null);
    }
    public DefaultGameWrapper(Game_Session__c session) {
        rejectWhenNull(session);

        this.id                 = session.Id;
        this.sessionCode        = session.Session_Code__c;

        this.result = new Result(null, null);
    }

    public DefaultGameWrapper setCurrentStep() {
        if (session == null)
            return this;
        if (session.Current_Step__c != null) 
            this.currentStep = new GameSessionUnitWrapper(session.Current_Step__r);

        return this;
    }

    private void rejectWhenNull(Game_Session__c session) {
        AuraHandledException auraRejected = new AuraHandledException(REJECTED_STRING);
        auraRejected.setMessage(REJECTED_STRING);
        
        if (session == null) throw auraRejected;
    } 
}