force-app/main/default/objects/Game_Session__c/Game_Session__c.object-meta.xml
<CustomObject>
    <label>Game Session</label>
    <nameField>
        <displayFormat>GS-{0000}</displayFormat>
        <label>Game Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/Game_Unit__c.object-meta.xml
<CustomObject>
    <label>Game Unit</label>
    <nameField>
        <displayFormat>GU-{0000}</displayFormat>
        <label>Game Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/fields/Game_Session__c.field-meta.xml
<CustomField>
    <fullName>Game_Session__c</fullName>
    <label>Game Session</label>
    <referenceTo>Game_Session__c</referenceTo>
    <relationshipLabel>Game Units</relationshipLabel>
    <relationshipName>Game_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Game_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Completion__e/Unit_Completion__e.object-meta.xml
<CustomObject>
    <label>Unit Completion</label>
    <pluralLabel>Unit Completions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Unit_Completion__e/fields/Game_Session__c.field-meta.xml
<CustomField>
    <fullName>Game_Session__c</fullName>
    <label>Game Session</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Completion__e/fields/Game_Unit_Id__c.field-meta.xml
<CustomField>
    <fullName>Game_Unit_Id__c</fullName>
    <label>Game Unit Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GameUnitHelper.cls
public with sharing class GameUnitHelper {
    public static Game_Unit__c returnCompletedUnit(Id unitId) {
        return new Game_Unit__c(
            Id = unitId,
            Status__c = 'Closed' //move to a separate class contstant
        );
    }
    public static Unit_Completion__e generateCompletionEvent(Id gameSessionId, Id unitId) {
        return new Unit_Completion__e(
            Game_Unit_Id__c = unitId,
            Game_Session__c = gameSessionId,
            Type__c         = 'Completed'
        );
    }
}