force-app/main/default/objects/Game_Session__c/Game_Session__c.object-meta.xml
<CustomObject>
    <label>Game Session</label>
    <nameField>
        <displayFormat>GS-{0000}</displayFormat>
        <label>Game Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/Game_Unit__c.object-meta.xml
<CustomObject>
    <label>Game Unit</label>
    <nameField>
        <displayFormat>GU-{0000}</displayFormat>
        <label>Game Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Unit__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Game_Unit__c/fields/Game_Session__c.field-meta.xml
<CustomField>
    <fullName>Game_Session__c</fullName>
    <label>Game Session</label>
    <referenceTo>Game_Session__c</referenceTo>
    <relationshipLabel>Game Units</relationshipLabel>
    <relationshipName>Game_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Game_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Item__c/Unit_Item__c.object-meta.xml
<CustomObject>
    <label>Unit Item</label>
    <nameField>
        <displayFormat>UI-{0000}</displayFormat>
        <label>Unit Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Item__c/fields/Game_Unit__c.field-meta.xml
<CustomField>
    <fullName>Game_Unit__c</fullName>
    <label>Game Unit</label>
    <referenceTo>Game_Unit__c</referenceTo>
    <relationshipLabel>Unit Items</relationshipLabel>
    <relationshipName>Unit_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GameUnitSelector.cls
public with sharing class GameUnitSelector extends Selector {
    private final static String OBJECT_NAME = 'Game_Unit__c';

    private static GameUnitSelector instance = null;

    private Set<String> fields = new Set<String>{
        'Id', 'Title__c', 'Content__c', 'Status__c', 'Duration__c', 'Responses_Left__c', 'Game_Session__r.Participants_Joined__c'
    };
    private Map<String, Set<String>> childUnitsFields = new Map<String, Set<String>> {
        'Unit_Items__r' => new Set<String>{'Answer__c'}
    };

    public GameUnitSelector() {
        super(OBJECT_NAME);
        this.setFields(this.fields);
        this.setChildFields(this.childUnitsFields);
    }

    public static GameUnitSelector getInstance() {
        if (instance == null) {
            instance = new GameUnitSelector();
        }
        return instance;
    }
    public List<Game_Unit__c> getRecordsByConjunction(Map<String,String> conditions) {
        List<Game_Unit__c> units = (List<Game_Unit__c>)this.selectByConjunction(conditions);
        return units.isEmpty() ? null : units;
    }
    public Game_Unit__c getRecordById(String id) {
        List<Game_Unit__c> units = (List<Game_Unit__c>)this.selectById(new Set<Id>{(Id)id});
        return units.isEmpty() ? null : units[FIRST_ELEMENT];
    }
}